# Web_Scrapping

## Atlantic Books - Non_Fiction

In [1]:
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
import re
import time
from tqdm import tqdm

In [2]:
driver = webdriver.Chrome()
base_url = 'https://atlanticbooks.com/collections/non-fiction'
driver.get(base_url)
time.sleep(3)

In [3]:
html_data = BeautifulSoup(driver.page_source, 'html.parser')
pages = int(html_data.find('a', {'class': 'pagination--item'}).text)
pages

2

In [4]:
Titles = []
Authors = []
Prices = []
Original_Prices = []
Genres = []
Discounts = []
Descriptions = []

In [5]:
for i in tqdm(range(pages)):
    url = f'https://atlanticbooks.com/collections/non-fiction?page={i + 1}'
    driver.get(url)
    time.sleep(3)
    html_data = BeautifulSoup(driver.page_source, 'html.parser')
    products = html_data.find_all('div', class_='productitem')
    
    for product in products:
        try:
            title = product.find('h2', {'class': 'productitem--title'}).text.strip() if product.find('h2', {'class': 'productitem--title'}) else 'No Title'
            Titles.append(title)
            
            author = product.find('p', {'class': 'clp-product-author'}).text.strip() if product.find('p', {'class': 'clp-product-author'}) else 'No Author'
            Authors.append(author)
            
            price = product.find('div', {'class': 'price__current price__current--on-sale'}).find('span', {'class': 'money'}).text.strip().replace('Rs.', '').strip() if product.find('div', {'class': 'price__current price__current--on-sale'}) else '0'
            Prices.append(price)
            
            original_price = product.find('div', {'class': 'price__compare-at--hidden'}).find('span', {'class': 'money'}).text.strip().replace('Rs.', '').strip() if product.find('div', {'class': 'price__compare-at--hidden'}) else '0'
            Original_Prices.append(original_price)

            discount = product.find('span', {'data-price-percent-saved': True}).text.strip()+"%" if product.find('span', {'data-price-percent-saved': True}) else '0'
            Discounts.append(discount)
            
            description = product.find('div', {'class': 'productitem--description'}).text.strip() if product.find('div', {'class': 'productitem--description'}) else 'No Description'
            Descriptions.append(description)
            
            Genres.append("Non-Fiction")
        
        except Exception as e:
            print(f"Error while extracting data from a product: {e}")

driver.quit()

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.82s/it]

In [6]:
data = {
    'Title': Titles,
    'Price': Prices,
    'Original_Price': Original_Prices,
    'Discount': Discounts,
    'Author': Authors,
    'Genres': Genres,
    'Description': Descriptions
}

df = pd.DataFrame(data)
df

,Title,Price,Original_Price,Discount,Author,Genres,Description
0,The Poverty of Philosophy,200.00,250.00,20%,Karl Marx,Non-Fiction,"“…they see in poverty nothing but poverty, wit..."
1,Relativity: The Special and General Theory,140.00,175.00,20%,Albert Einstein,Non-Fiction,“The important thing is not to stop questionin...
2,Candide,120.00,150.00,20%,Voltaire,Non-Fiction,"Candide, a privileged and sheltered young man,..."
3,Essays: First and Second Series,236.00,295.00,0,Ralph Waldo Emerson,Non-Fiction,Ralph Waldo Emerson's Essays: First and Second...
4,The Upanishads,120.00,150.00,20%,Swami Paramananda,Non-Fiction,Swami Paramananda's The Upanishads explores an...
...,...,...,...,...,...,...,...
56,Confessions of an English Opium Eater,196.00,245.00,20%,Thomas De Quincey,Non-Fiction,Confessions of an English Opium-Eater is Thoma...
57,Autobiography of a Yogi,236.00,295.00,20%,Paramahansa Yogananda,Non-Fiction,"The goal of yoga science is to calm the mind, ..."
58,Aristotle's Politics,180.00,225.00,20%,Translated by Benjamin Jowett,Non-Fiction,Politics is a work of political philosophy by ...
59,A Portrait Of The Artist As A Young Man,156.00,195.00,20%,James Joyce,Non-Fiction,James Joyce was and remains unique among novel...
60,24 The Challenging New Number Puzzle,120.00,150.00,20%,John Enock,Non-Fiction,‘24’ is a challenging new cross-number puzzle ...

## Atlantic Books -Fiction

In [7]:
driver1 = webdriver.Chrome()
base_url1 = 'https://atlanticbooks.com/collections/fiction'
driver1.get(base_url1)
time.sleep(3)

In [8]:
html_data1 = BeautifulSoup(driver1.page_source, 'html.parser')
pages1 = int(html_data1.find('a', {'class': 'pagination--item'}).text)
pages1

2

In [9]:
Title = []
Author = []
Price = []
Original_Price = []
Genre = []
Discount = []
Description = []

In [10]:
for i in tqdm(range(pages1)):  
    url1 = f'https://atlanticbooks.com/collections/fiction?page={i + 1}' 
    driver1.get(url1)  
    time.sleep(3) 
    html_data1 = BeautifulSoup(driver1.page_source, 'html.parser')
    products = html_data1.find_all('div', class_='productitem') 
    
    for product in products:
        try:
            title = product.find('h2', {'class': 'productitem--title'}).text.strip() if product.find('h2', {'class': 'productitem--title'}) else 'No Title'
            Title.append(title)
            author = product.find('p', {'class': 'clp-product-author'}).text.strip() if product.find('p', {'class': 'clp-product-author'}) else 'No Author'
            Author.append(author)
            price = product.find('div', {'class': 'price__current price__current--on-sale'}).find('span', {'class': 'money'}).text.strip().replace('Rs.', '').strip() if product.find('div', {'class': 'price__current price__current--on-sale'}) else 'No Price'
            Price.append(price)
            original_price = product.find('div', {'class': 'price__compare-at--hidden'}).find('span', {'class': 'money'}).text.strip().replace('Rs.', '').strip() if product.find('div', {'class': 'price__compare-at--hidden'}) else '0'
            Original_Price.append(original_price)
            discount = product.find('span', {'data-price-percent-saved': True}).text.strip() + "%" if product.find('span', {'data-price-percent-saved': True}) else 'No Discount'
            Discount.append(discount)
            description = product.find('div', {'class': 'productitem--description'}).text.strip() if product.find('div', {'class': 'productitem--description'}) else 'No Description'
            Description.append(description)
            Genre.append("Fiction")
        
        except Exception as e:
            print(f"Error while extracting data from a product: {e}")

driver1.quit()

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.96s/it]

In [11]:
data1 = {
    'Title': Title,
    'Price': Price,
    'Original_Price': Original_Price,
    'Discount': Discount,
    'Author': Author,
    'Genres': Genre,
    'Description': Description
}

df1 = pd.DataFrame(data1)
df1

,Title,Price,Original_Price,Discount,Author,Genres,Description
0,Volpone,116.00,145.00,20%,Ben Jonson,Fiction,"Volpone (or The Fox) is a comedy in five acts,..."
1,Twelfth Night,100.00,125.00,20%,William Shakespeare,Fiction,"Twelfth Night is a tale of unrequited love, hi..."
2,The Rudyard Kipling Collection,679.00,849.00,20%,Rudyard Kipling,Fiction,"(1) The Jungle Books: - Kipling's allegory, Th..."
3,The Old Man and the Sea,100.00,125.00,20%,Ernest Hemingway,Fiction,"“But man is not made for defeat,” he said. “A ..."
4,Pride And Prejudice,236.00,295.00,20%,Jane Austen,Fiction,In the delightful social comedy of Pride and P...
...,...,...,...,...,...,...,...
91,The Hound of the Baskervilles,156.00,195.00,20%,A. Conan Doyle,Fiction,The Hound of the Baskervilles is Sir Arthur Co...
92,The Adventures Of Sherlock Holmes,236.00,295.00,20%,Sir Arthur Conan Doyle,Fiction,The Adventures of Sherlock Holmes is a collect...
93,Story Of A Young Lawyer,100.00,125.00,20%,Panchajanya Batra Singh,Fiction,Newly married Tara struggles through the forma...
94,Northanger Abbey,120.00,150.00,20%,Jane Austen,Fiction,"Northanger Abbey, written during the same peri..."
95,Middlemarch,280.00,350.00,No Discount,George Eliot,Fiction,Special Features: enotes.com Middlemarch (Cycl...

### saving df and df1

In [13]:
df.to_csv('non_fiction_books.csv', index=False)
df1.to_csv('fiction_books.csv', index=False)